version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    env_file: .env
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=pia
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASS}
      - OPENVPN_PROTOCOL=tcp
      - REGION=${VPN_REGION}
      - FIREWALL=on
      - HTTPPROXY=on
      - HTTP_CONTROL_SERVER=on
      - PORT_FORWARDING=on                                   # Enable PIA port forwarding
      - PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port  # Save port to file
      - VPN_PORT_FORWARDING_UP_COMMAND=sh -c "apk add --no-cache docker-cli && docker exec rtorrent-rutorrent /scripts/update-port.sh"
    volumes:
      - ./gluetun:/gluetun  # Stores forwarded_port file
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "6901:6901"         # For noVNC Firefox - for example together with https://addons.mozilla.org/en-US/firefox/addon/xirvik-torrent-to-seedbox-uplo/
      - "8080:8080"         # For rutorrent web UI
      - "8888:8888/tcp"     # For HTTPPROXY
    restart: unless-stopped

  rtorrent-rutorrent:
    image: docker.io/crazymax/rtorrent-rutorrent:latest
    container_name: rtorrent-rutorrent
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    volumes:
      - ./rtorrent-data:/downloads
      - ./gluetun:/gluetun:ro  # Read-only access to forwarded_port
      - ./scripts:/scripts
      - ./passwd:/passwd
    environment:
      - PUID=1000
      - PGID=1000
      - RUTORRENT_PORT=8080
      - XMLRPC_PORT=5000
      - RT_INC_PORT=20000
    restart: unless-stopped


  firefox-using-volumes:
    image: accetto/ubuntu-vnc-xfce-firefox-g3:latest
    container_name: firefox_gluetun
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
    shm_size: "256m"
    environment:
      - VNC_RESOLUTION=1700x900
      - VNC_PW=${VNC_PW:-headless}
    volumes:
      - type: volume
        source: firefox-profile-volume
        target: /home/headless/.mozilla/firefox

volumes:
  firefox-profile-volume:
